
"use client";

import { Button } from "@/components/ui/button";
import { ArrowRight, Wand2 } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useAuth } from "@/hooks/use-auth";

const examples = [
  {
    prompt: "A futuristic cityscape at dusk, with flying cars and towering neon skyscrapers.",
    imageUrl: "https://i.postimg.cc/dQ9DY41x/generated-image-2.png",
    aiHint: "futuristic city"
  },
  {
    prompt: "A majestic lion with a crown made of stars, standing on a cosmic cloud.",
    imageUrl: "https://i.postimg.cc/kX6rcgkv/generated-image-3.png",
    aiHint: "majestic lion"
  },
  {
    prompt: "An enchanted forest with glowing mushrooms and a river of liquid moonlight.",
    imageUrl: "https://i.postimg.cc/yYdRpwPP/generated-image-4.png",
    aiHint: "enchanted forest"
  },
  {
    prompt: "A cute, fluffy robot tending to a garden on Mars.",
    imageUrl: "https://i.postimg.cc/fbxS0Zzw/generated-image-5.png",
    aiHint: "robot garden"
  },
  {
    prompt: "A surreal painting of a clock melting over a desert landscape, in the style of Salvador Dalí.",
    imageUrl: "https://i.postimg.cc/yNzkK5F2/a-surreal-painting-of-a-clock-melting-ov-6-SMab-J5-WS3-Cn-TG6bn-HNHJg-wo-V-vkw2-T42-A0-F0-PJu-Zidg.jpg",
    aiHint: "surreal painting"
  },
  {
    prompt: "A photorealistic image of an astronaut riding a horse on the moon.",
    imageUrl: "https://i.postimg.cc/kGk7c6sL/generated-image-6.png",
    aiHint: "astronaut horse"
  },
    {
    prompt: "A dragon made of pure crystal, sleeping on a hoard of jewels.",
    imageUrl: "https://i.postimg.cc/vZ7GrmVS/generated-image-7.png",
    aiHint: "crystal dragon"
  },
  {
    prompt: "A steampunk submarine exploring a vibrant underwater coral reef.",
    imageUrl: "https://i.postimg.cc/j2JbLqTc/generated-image-8.png",
    aiHint: "steampunk submarine"
  },
];

export default function TextToImageExamplesPage() {
  const { user } = useAuth();
  const ctaLink = user ? "/dashboard#text-to-image" : "/signup";

  return (
    <div className="container mx-auto px-4 py-12 md:py-20 flex-1">
      <div className="text-center mb-12">
        <div className="inline-flex items-center gap-2 px-4 py-1 mb-4 text-sm font-medium text-primary bg-primary/10 border border-primary/20 rounded-full">
            <Wand2 className="w-4 h-4" />
            <span>Text-to-Image Showcase</span>
        </div>
        <h1 className="text-4xl md:text-5xl font-bold font-headline tracking-tight bg-gradient-to-r from-primary via-accent to-blue-400 text-transparent bg-clip-text">Gallery of Imagination</h1>
        <p className="mt-4 text-lg text-muted-foreground max-w-2xl mx-auto">
          Explore the incredible images generated by our AI. Your words are the only limit.
        </p>
         <Link href={ctaLink} className="mt-6 inline-block">
            <Button size="lg">
                Try it Yourself <ArrowRight className="w-4 h-4 ml-2" />
            </Button>
        </Link>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 md:gap-6">
        {examples.map((example, index) => (
          <div key={index} className="group relative overflow-hidden rounded-lg shadow-lg">
            <Image
              src={example.imageUrl}
              alt={example.prompt}
              width={512}
              height={512}
              className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
              data-ai-hint={example.aiHint}
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent">
              <div className="absolute bottom-0 left-0 p-4">
                <p className="text-sm text-white/90">{example.prompt}</p>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
